const courses = [
  {
    id: 1,
    title: "Frontend (HTML, CSS, JS)",
    price: 30,
    teacher: "Ali Valiyev",
    category: "Frontend",
    duration: "5 hafta",
    lessonsCount: 25,
    studentsCount: 150,
    currentStudents: 110,
    videoHours: 35,
    image: "https://picsum.photos/400/250?1",
  },
  {
    id: 2,
    title: "React JS Pro",
    price: 50,
    teacher: "Sardor Karimov",
    category: "Frontend",
    duration: "8 hafta",
    lessonsCount: 40,
    studentsCount: 200,
    currentStudents: 160,
    videoHours: 55,
    image: "https://picsum.photos/400/250?2",
  },
  {
    id: 3,
    title: "Vue.js 3 Masterclass",
    price: 45,
    teacher: "Jasur Tursunov",
    category: "Frontend",
    duration: "6 hafta",
    lessonsCount: 30,
    studentsCount: 180,
    currentStudents: 130,
    videoHours: 42,
    image: "https://picsum.photos/400/250?3",
  },
  {
    id: 4,
    title: "Node.js Backend",
    price: 40,
    teacher: "Aziz Xasanov",
    category: "Backend",
    duration: "6 hafta",
    lessonsCount: 28,
    studentsCount: 160,
    currentStudents: 120,
    videoHours: 38,
    image: "https://picsum.photos/400/250?4",
  },
  {
    id: 5,
    title: "Python Backend",
    price: 35,
    teacher: "Dilshod Yo‘ldoshev",
    category: "Backend",
    duration: "5 hafta",
    lessonsCount: 24,
    studentsCount: 170,
    currentStudents: 125,
    videoHours: 36,
    image: "https://picsum.photos/400/250?5",
  },

  {
    id: 6,
    title: "Flutter Mobile App",
    price: 55,
    teacher: "Sherzod Usmonov",
    category: "Mobile",
    duration: "7 hafta",
    lessonsCount: 35,
    studentsCount: 140,
    currentStudents: 100,
    videoHours: 48,
    image: "https://picsum.photos/400/250?6",
  },
  {
    id: 7,
    title: "Android Kotlin",
    price: 50,
    teacher: "Bobur Xasanov",
    category: "Mobile",
    duration: "6 hafta",
    lessonsCount: 30,
    studentsCount: 130,
    currentStudents: 95,
    videoHours: 42,
    image: "https://picsum.photos/400/250?7",
  },
  {
    id: 8,
    title: "UI/UX Design",
    price: 30,
    teacher: "Malika Ismoilova",
    category: "Design",
    duration: "4 hafta",
    lessonsCount: 20,
    studentsCount: 110,
    currentStudents: 80,
    videoHours: 25,
    image: "https://picsum.photos/400/250?8",
  },
  {
    id: 9,
    title: "Graphic Design (Photoshop)",
    price: 25,
    teacher: "Shahzoda Karimova",
    category: "Design",
    duration: "4 hafta",
    lessonsCount: 18,
    studentsCount: 120,
    currentStudents: 90,
    videoHours: 22,
    image: "https://picsum.photos/400/250?9",
  },
  {
    id: 10,
    title: "Figma Design",
    price: 20,
    teacher: "Madina Rahimova",
    category: "Design",
    duration: "3 hafta",
    lessonsCount: 15,
    studentsCount: 95,
    currentStudents: 70,
    videoHours: 18,
    image: "https://picsum.photos/400/250?10",
  },

  {
    id: 11,
    title: "SMM Manager",
    price: 25,
    teacher: "Oybek Nazarov",
    category: "Marketing",
    duration: "4 hafta",
    lessonsCount: 20,
    studentsCount: 180,
    currentStudents: 140,
    videoHours: 28,
    image: "https://picsum.photos/400/250?11",
  },
  {
    id: 12,
    title: "Target Reklama (Facebook Ads)",
    price: 30,
    teacher: "Akmal Raximov",
    category: "Marketing",
    duration: "4 hafta",
    lessonsCount: 18,
    studentsCount: 150,
    currentStudents: 110,
    videoHours: 24,
    image: "https://picsum.photos/400/250?12",
  },
  {
    id: 13,
    title: "Copywriting",
    price: 20,
    teacher: "Javlonbek Qodirov",
    category: "Marketing",
    duration: "3 hafta",
    lessonsCount: 14,
    studentsCount: 130,
    currentStudents: 95,
    videoHours: 16,
    image: "https://picsum.photos/400/250?13",
  },
  {
    id: 14,
    title: "Video Montaj (Premiere Pro)",
    price: 35,
    teacher: "Saidbek Tursunov",
    category: "Media",
    duration: "5 hafta",
    lessonsCount: 22,
    studentsCount: 140,
    currentStudents: 100,
    videoHours: 30,
    image: "https://picsum.photos/400/250?14",
  },
  {
    id: 15,
    title: "Motion Design (After Effects)",
    price: 45,
    teacher: "Ulug‘bek Saidov",
    category: "Media",
    duration: "6 hafta",
    lessonsCount: 28,
    studentsCount: 120,
    currentStudents: 85,
    videoHours: 38,
    image: "https://picsum.photos/400/250?15",
  },

  {
    id: 16,
    title: "Data Science",
    price: 70,
    teacher: "Kamola Yusupova",
    category: "Data",
    duration: "10 hafta",
    lessonsCount: 50,
    studentsCount: 110,
    currentStudents: 80,
    videoHours: 65,
    image: "https://picsum.photos/400/250?16",
  },
  {
    id: 17,
    title: "Machine Learning",
    price: 80,
    teacher: "Anvar Xolmatov",
    category: "AI",
    duration: "12 hafta",
    lessonsCount: 60,
    studentsCount: 100,
    currentStudents: 70,
    videoHours: 80,
    image: "https://picsum.photos/400/250?17",
  },
  {
    id: 18,
    title: "Cyber Security",
    price: 60,
    teacher: "Rustam Akbarov",
    category: "Security",
    duration: "8 hafta",
    lessonsCount: 40,
    studentsCount: 90,
    currentStudents: 60,
    videoHours: 55,
    image: "https://picsum.photos/400/250?18",
  },
  {
    id: 19,
    title: "DevOps Engineering",
    price: 65,
    teacher: "Islom Rustamov",
    category: "DevOps",
    duration: "9 hafta",
    lessonsCount: 45,
    studentsCount: 95,
    currentStudents: 70,
    videoHours: 60,
    image: "https://picsum.photos/400/250?19",
  },
  {
    id: 20,
    title: "AI Tools & Automation",
    price: 40,
    teacher: "Bekzod Aliyev",
    category: "AI",
    duration: "5 hafta",
    lessonsCount: 25,
    studentsCount: 200,
    currentStudents: 150,
    videoHours: 35,
    image: "https://picsum.photos/400/250?20",
  },
];

export default courses;
