import { defineStore } from 'pinia'
import { ref } from 'vue'

export const useSettingsStore = defineStore('settings', () => {
    const lang = ref(localStorage.getItem('lang') || 'uz')

    const translations = {
        uz: {
            home: 'Bosh sahifa',
            course: 'Kurslar',
            blog: 'Blog',
            page: 'Sahifalar',
            contact: 'Aloqa',
            faqs: 'Ko\'p so\'raladigan savollar',
            error: 'Xatolik',
            about: 'O\'qituvchilar',
            signin: 'Kirish',
            profile: 'Profil',
            exit: 'Chiqish',
            search: 'Qidirish',
            searchPlaceholder: 'Nimani qidiryapsiz?',
            heroTitle: 'Biz bilan ulkan natijalarga erishing',
            heroDesc: 'Rizvojlanish uchun imkoniyatni qo\'ldan boy bermang',
            heroBtn: 'Fikr qoldirish',
            featuredTitle: 'Yangi kurslar',
            exploreBtn: 'Barchasini ko\'r',
            free: 'Bepul',
            lessons: 'darslar',
            results: 'natijalar',
            viewMore: 'Batafsil',
            myProfile: 'Mening profilim',
            personalInfo: 'Shaxsiy ma\'lumotlar',
            enrolledCourses: "Ro'yxatdan o'tgan kurslar",
            editProfile: 'Profilni tahrirlash',
            saveChanges: 'O\'zgarishlarni saqlash',
            cancel: 'Bekor qilish',
            fullName: 'To\'liq ism',
            email: 'Email manzili',
            username: 'Foydalanuvchi nomi'
        },
        en: {
            home: 'Home',
            course: 'Course',
            blog: 'Blog',
            page: 'Page',
            contact: 'Contact',
            faqs: 'FAQs',
            error: 'Error',
            about: 'Teachers',
            signin: 'Sign In',
            profile: 'Profile',
            exit: 'Exit',
            search: 'Search',
            searchPlaceholder: 'What are you looking for?',
            heroTitle: 'Achieve great results with us',
            heroDesc: 'Don\'t miss the opportunity to grow',
            heroBtn: 'Leave feedback',
            featuredTitle: 'New courses',
            exploreBtn: 'View all',
            free: 'Free',
            lessons: 'lessons',
            results: 'results',
            viewMore: 'View More',
            myProfile: 'My Profile',
            personalInfo: 'Personal Information',
            enrolledCourses: 'Enrolled Courses',
            editProfile: 'Edit Profile',
            saveChanges: 'Save Changes',
            cancel: 'Cancel',
            fullName: 'Full Name',
            email: 'Email Address',
            username: 'Username'
        },
        ru: {
            home: 'Главная',
            course: 'Курсы',
            blog: 'Блог',
            page: 'Страницы',
            contact: 'Контакт',
            faqs: 'Часто задаваемые вопросы',
            error: 'Ошибка',
            about: 'Учителя',
            signin: 'Войти',
            profile: 'Профиль',
            exit: 'Выйти',
            search: 'Поиск',
            searchPlaceholder: 'Что вы ищете?',
            heroTitle: 'Добивайтесь отличных результатов с нами',
            heroDesc: 'Не упустите возможность развиваться',
            heroBtn: 'Оставить отзыв',
            featuredTitle: 'Новые курсы',
            exploreBtn: 'Посмотреть все',
            free: 'Бесплатно',
            lessons: 'уроков',
            results: 'результатов',
            viewMore: 'Подробнее',
            myProfile: 'Мой профиль',
            personalInfo: 'Личная информация',
            enrolledCourses: 'Мои курсы',
            editProfile: 'Редактировать профиль',
            saveChanges: 'Сохранить изменения',
            cancel: 'Отмена',
            fullName: 'Полное имя',
            email: 'Email адрес',
            username: 'Имя пользователя'
        },
        ja: {
            home: 'ホーム',
            course: 'コース',
            blog: 'ブログ',
            page: 'ページ',
            contact: 'お問い合わせ',
            faqs: 'よくある質問',
            error: 'エラー',
            about: '先生',
            signin: 'サインイン',
            profile: 'プロフィール',
            exit: '退出',
            search: '検索',
            searchPlaceholder: '何をお探しですか？',
            heroTitle: '私たちと一緒に素晴らしい結果を達成しましょう',
            heroDesc: '成長の機会を逃さないでください',
            heroBtn: 'フィードバックを残す',
            featuredTitle: '新しいコース',
            exploreBtn: 'すべて表示',
            free: '無料',
            lessons: 'レッスン',
            results: '結果',
            viewMore: 'もっと見る',
            myProfile: 'マイプロフィール',
            personalInfo: '個人情報',
            enrolledCourses: '受講中のコース',
            editProfile: 'プロフィールを編集',
            saveChanges: '変更を保存',
            cancel: 'キャンセル',
            fullName: 'フルネーム',
            email: 'メールアドレス',
            username: 'ユーザー名'
        }
    };

    const t = (key) => translations[lang.value][key] || key;

    const setLang = (newLang) => {
        lang.value = newLang
        localStorage.setItem('lang', newLang)
    }

    return { lang, setLang, t }
})
